import type { Look } from "../scene/looks.js";
import type { SceneFrame } from "./scenes.js";
import { fontFaces, HANDOFF } from "./scenes.js";

/**
 * The project files around the compositions.
 *
 * HyperFrames' production loop assumes a shape, and matching it is the point of
 * this file: a design spec the frame authors read, a storyboard that is the
 * plan layer, and an index that assembles scenes as sub-compositions on tracks.
 * A directory that merely happens to contain renderable HTML is not the same
 * thing — Studio reads the storyboard as a contact sheet, and every later step
 * of theirs resolves the design spec by name.
 */

/**
 * `frame.md` — the design spec.
 *
 * Their format precisely: YAML frontmatter is the **normative** layer, holding
 * the real machine-readable tokens, and the prose below is context. Named
 * `frame.md` lowercase, which is the video-first spec and wins over `design.md`
 * when both exist.
 *
 * Reel writes it from the look the film was composed in, so the spec and the
 * cut cannot disagree — and so an agent editing a scene afterwards has the
 * tokens to hand rather than having to read them back out of the CSS.
 */
export function frameMd(look: Look, accent: string, name: string, frame: { width: number; height: number }): string {
  return `---
name: ${name} — ${look.name}
format: ${frame.width}x${frame.height}
colors:
  ground: "${look.ground}"
  ink: "${look.ink}"
  muted: "${look.muted}"
  accent: "${accent}"
typography:
  display:
    fontFamily: ${look.display}
    fontWeight: ${look.displayWeight}
    letterSpacing: "${look.tracking}"
    textTransform: ${look.transform}
  label:
    fontFamily: ${look.label}
    letterSpacing: "0.26em"
    textTransform: uppercase
motion:
  entrance: waterfall
  wordDuration: 0.16s
  ease: power4.out
  handoff: 0.5s
---

# ${name} — the frame

Generated by \`reel compose\` from the **${look.name}** look. ${look.mood}

## The frame

The unit is the frame, not the page. One very large element and everything else
small; a card that tries to be balanced reads as a slide.

## Colour

\`accent\` is the brand's, and every backdrop in this film is built out of it —
hue-rotated, tinted, blurred. That is deliberate: the same look on two products
should not produce the same picture. Ground and ink belong to the look and
should not be edited per scene.

## Motion

Arrivals are **binary and fast**. A word is revealed with a zero-duration
\`set\` and whipped into place in ~0.16s on \`power4.out\`; it is never faded in.
Fading an arrival is the single change that turns a title card into a slide.

Backdrops move for a scene's whole duration. A bloom that stops once the words
have landed leaves the frame dead for the rest of the shot.

## Do

- Cut on the beats in \`shots.json\`. They are exact, because the driver caused them.
- Keep cards to 2.5–3.5s.
- Let scenes dissolve into each other. The handoff is written in \`index.html\`,
  which is the only layer that can see both sides of a seam.

## Don't

- Don't crop the footage to fill the frame. A product demo cropped loses the
  thing it is about.
- Don't lay text over the picture. The app moves; a bottom band does not collide.
- Don't animate a scene's exit. The transition **is** the exit, and a scene that
  fades itself out before one that fades itself in is a jump cut with a dip.
`;
}

/**
 * `STORYBOARD.md` — the plan layer.
 *
 * Their format: YAML frontmatter for global direction, then one
 * `## Frame N — Title` per scene with `- key: value` metadata. The parser is
 * lenient and Studio renders it as a contact sheet, so it is worth writing
 * properly even though nothing here reads it back yet.
 */
export function storyboardMd(
  frames: SceneFrame[],
  opts: {
    name: string;
    width: number;
    height: number;
    duration: number;
    message: string;
    /** Written once at the top; every scene inherits it. */
    direction?: string;
  },
): string {
  const head = `---
format: ${opts.width}x${opts.height}
duration: ${opts.duration.toFixed(1)}s
message: ${opts.message}
arc: Title → Product → Chapter → Command line → Close
audience: developers evaluating the tool
mode: autonomous
---

# ${opts.name}

Assembled by \`reel compose\`. Every frame below is a sub-composition mounted by
\`index.html\`; the footage frames are real recordings of the running app, and
their captions and camera moves are timed from the shot manifest the driver
wrote while filming.

Each frame carries a **time-coded shot sequence** — the windows the scene
develops across. The windows are derived: for a footage scene they are the
driver's own cues, and every beat and sound below is a recorded fact rather than
an estimate. The **direction inside each window is not written yet**, and that
is the authoring pass: replace each \`TODO\` with what is on screen, what moves,
and where it sits.

${opts.direction ?? ""}`;

  // Durations to the millisecond, which is finer than a plan layer needs and
  // exactly what the contract needs: `assemble` re-derives every scene's start
  // from these, so a duration rounded to 10ms moves the back half of the film
  // by a frame and puts the seams a frame off the scenes they belong to.
  const body = frames
    .map(
      (f, i) => `
## Frame ${i + 1} — ${f.title}

- status: built
- src: ${f.src}
- duration: ${f.duration.toFixed(3)}s
- transition_in: ${f.transitionIn}
- scene: ${f.scene}
- poster: ${f.poster.toFixed(2)}${f.voiceover ? `
- voiceover: ${f.voiceover.replace(/\n/g, " ")}` : ""}
${f.sequence ? `\n${f.sequence}\n` : ""}`,
    )
    .join("");

  return head + body;
}

/**
 * `index.html` — the assembly layer, and nothing else.
 *
 * Each scene is a host clip carrying `data-composition-src` plus its own
 * `data-start` / `data-duration` / `data-track-index` / `data-width` /
 * `data-height`. The host's `data-composition-id` must equal the id inside the
 * mounted file *and* the key that file registers its timeline under; a mismatch
 * passes lint and then waits 45 seconds per scene at render before capturing
 * static frames.
 *
 * The host's own timeline is deliberately thin: a grade, the seams, and the
 * music ducking. Everything else belongs to the scene that owns it, which is
 * what makes a scene editable without reading the rest of the cut. The seams
 * are the exception, and they have to be — a transition animates two scenes at
 * once, and this is the only layer that can see both.
 */
export interface MusicBed {
  /** Path to the track, relative to index.html. */
  file: string;
  /** Resting level, 0-1. */
  level: number;
  /** Spans where narration is speaking, in composition time. */
  duckAt: { at: number; dur: number }[];
}

/**
 * The slice of a look the host actually paints.
 *
 * Narrower than `Look` on purpose: `assemble` rebuilds the index long after
 * `compose` ran, from a sidecar rather than from a resolved look, and a frame
 * preset it would have to re-resolve may not even be installed by then. Five
 * scalars travel; a `Look` satisfies this structurally, so compose passes its
 * own straight through.
 */
export interface AssemblyLook {
  ground: string;
  ink: string;
  dark: boolean;
  display: string;
  label: string;
}

export function indexHtml(
  frames: SceneFrame[],
  look: AssemblyLook,
  opts: { id: string; width: number; height: number; fps: number; duration: number; music?: MusicBed },
): string {
  const clips = frames
    .map(
      (f, i) =>
        // Every host clip carries an id. Without one Studio has no stable edit
        // target for its timeline and canvas controls, and `check` says so.
        `    <div id="scene-${f.id}" data-composition-id="${f.id}"\n` +
        `         data-composition-src="${f.src}"\n` +
        `         data-start="${f.at.toFixed(3)}" data-duration="${f.duration.toFixed(3)}"\n` +
        `         data-track-index="${i}" data-width="${opts.width}" data-height="${opts.height}"></div>`,
    )
    .join("\n\n");

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <!-- Vendored, never linked. A render that fetches depends on someone
         else's uptime and fails outright in a sandbox. -->
    <script src="./gsap.min.js"></script>
    <style>
${fontFaces(look.display, look.label)}
      * { margin: 0; padding: 0; box-sizing: border-box; }
      html, body { width: ${opts.width}px; height: ${opts.height}px; overflow: hidden; background: #000; }
      #root { position: relative; overflow: hidden; background: ${look.ground}; }
      /* The grade sits over every scene for the whole film — a vignette that
         breathes, and the one thing the index itself animates. Untimed, so it
         needs its own layout: the runtime only positions elements carrying
         data-start. */
      /* The seam flash. Above every scene, below the grade — an edit happens to
         the picture, not to the grade laid over it.
         It flashes *away* from the ground: white on a dark film reads as
         overexposure, but white on a cream one has no contrast to spend and
         only blows the frame out. On a light look it dips to the ink instead,
         which is the same edit read the other way up. */
      #flash { position: absolute; inset: 0; opacity: 0; pointer-events: none; z-index: 40;
        background: ${look.dark ? "#ffffff" : look.ink}; }
      #grade { position: absolute; inset: 0; pointer-events: none; z-index: 50;
        background: radial-gradient(ellipse at 50% 48%, transparent 52%,
          ${look.dark ? "rgba(0,0,0,.55)" : "rgba(20,16,12,.28)"} 100%); }
    </style>
  </head>
  <body>
    <div id="root" data-composition-id="${opts.id}" data-start="0"
         data-duration="${opts.duration.toFixed(3)}"
         data-width="${opts.width}" data-height="${opts.height}" data-fps="${opts.fps}">

${clips}

      <div id="flash"></div>
${opts.music ? `      <audio id="bed" src="${opts.music.file}" data-start="0"\n           data-duration="${opts.duration.toFixed(3)}" data-volume="${opts.music.level}"></audio>\n` : ""}
      <div id="grade"></div>
    </div>

    <script>
      // The host registers a timeline of its own. The runtime auto-nests every
      // registered child timeline under it, so this file stays a running order
      // — but a composition with no registry entry at all is an error, and the
      // grade gives this one something real to drive.
      var tl = gsap.timeline({ paused: true });
      tl.fromTo("#grade", { opacity: .55 }, { opacity: .95, duration: ${opts.duration.toFixed(3)}, ease: "none" }, 0);
${transitionTweens(frames, HANDOFF, look.dark ? 0.62 : 0.42)}
${duckTweens(opts.music)}
      window.__timelines["${opts.id}"] = tl;
    </script>
  </body>
</html>
`;
}

/**
 * The seams between scenes.
 *
 * ## Why this lives in the index and not in the scenes
 *
 * Their rule, and it is not a style preference: *exit animations are banned —
 * the transition IS the exit, and the outgoing scene must be fully visible when
 * it starts.* A scene that fades itself out, followed by a scene that fades
 * itself in, is a jump cut with a dip. This code used to do exactly that.
 *
 * A real transition animates both sides at the same instant, so it has to be
 * written by the only layer that can see both: the index. Scene sub-compositions
 * cannot reach each other, and a sub-composition timeline cannot touch the host.
 *
 * ## The vocabulary
 *
 * One primary and one accent, which is their guidance — *"pick ONE primary
 * (60–70% of scene changes) + 1–2 accents; never use a different transition for
 * every scene"*. A product demo is medium energy, so:
 *
 *  - **blur crossfade** everywhere, the recipe from `css-dissolve.md`: the
 *    outgoing blurs and swells slightly as it goes, the incoming arrives from
 *    under a blur a beat later.
 *  - **overexposure flash** into a chapter card, because that seam is a section
 *    break rather than a continuation, and white at the cut reads as an edit.
 *
 * Every tween ends with a zero-duration `set` on the clip boundary. An opacity
 * tween that merely *reaches* zero there leaves stale state when the renderer
 * seeks out of order — their linter calls it `gsap_exit_missing_hard_kill`.
 */
function transitionTweens(frames: SceneFrame[], handoff: number, peak: number): string {
  const out: string[] = [];
  for (let i = 1; i < frames.length; i++) {
    const prev = frames[i - 1]!;
    const next = frames[i]!;
    const T = Number(next.at.toFixed(3));
    const prevEnd = Number((prev.at + prev.duration).toFixed(3));
    const from = `"#scene-${prev.id}"`;
    const to = `"#scene-${next.id}"`;
    const flash = next.transitionIn === "flash";

    out.push(`      // ${prev.title} → ${next.title} (${next.transitionIn})`);
    out.push(
      `      tl.to(${from}, { filter: "blur(10px)", scale: 1.03, opacity: 0, duration: ${handoff}, ease: "power2.inOut" }, ${T});`,
      // The hard kill: a seek landing past the fade gets the resolved state
      // rather than whatever the tween last wrote.
      `      tl.set(${from}, { opacity: 0 }, ${prevEnd});`,
      `      tl.fromTo(${to}, { filter: "blur(10px)", scale: .97, opacity: 0 },` +
        ` { filter: "blur(0px)", scale: 1, opacity: 1, duration: ${handoff}, ease: "power2.inOut" }, ${Number((T + 0.1).toFixed(3))});`,
    );
    if (flash) {
      out.push(
        `      tl.to("#flash", { opacity: ${peak}, duration: .14, ease: "power2.out" }, ${Number((T + 0.06).toFixed(3))});`,
        `      tl.to("#flash", { opacity: 0, duration: .34, ease: "power2.in" }, ${Number((T + 0.2).toFixed(3))});`,
      );
    }
  }
  return out.join("\n");
}

/**
 * Duck the bed under every spoken line.
 *
 * A music bed that holds one level through narration is the reason people reach
 * for the volume control: the voice and the pad occupy the same few hundred
 * hertz, and the ear cannot separate them by loudness alone. Dropping the bed
 * roughly 12dB while a line runs, and bringing it back over half a second, is
 * the whole trick.
 *
 * Timed off the narration cues rather than measured from the audio — the driver
 * knows when each line starts because it scheduled it, and a level automation
 * derived from the waveform would only ever be an estimate of that.
 */
function duckTweens(music: MusicBed | undefined): string {
  if (!music || music.duckAt.length === 0) return "";
  const lines: string[] = [];
  const ducked = Number((music.level * 0.25).toFixed(3));
  for (const span of music.duckAt) {
    const at = Number(Math.max(0, span.at - 0.35).toFixed(3));
    const back = Number((span.at + span.dur).toFixed(3));
    lines.push(
      `      tl.to("#bed", { volume: ${ducked}, duration: .35, ease: "power2.out" }, ${at});`,
      `      tl.to("#bed", { volume: ${music.level}, duration: .6, ease: "power2.inOut" }, ${back});`,
    );
  }
  return lines.join("\n");
}

/** The manifest that makes a directory a project its CLI recognises. */
export function hyperframesJson(name: string): string {
  return JSON.stringify({ name, entry: "index.html" }, null, 2) + "\n";
}
