import type { Look } from "../scene/looks.js";
import type { SceneFrame } from "./scenes.js";
import { fontFaces } from "./scenes.js";

/**
 * The project files around the compositions.
 *
 * HyperFrames' production loop assumes a shape, and matching it is the point of
 * this file: a design spec the frame authors read, a storyboard that is the
 * plan layer, and an index that assembles scenes as sub-compositions on tracks.
 * A directory that merely happens to contain renderable HTML is not the same
 * thing — Studio reads the storyboard as a contact sheet, and every later step
 * of theirs resolves the design spec by name.
 */

/**
 * `frame.md` — the design spec.
 *
 * Their format precisely: YAML frontmatter is the **normative** layer, holding
 * the real machine-readable tokens, and the prose below is context. Named
 * `frame.md` lowercase, which is the video-first spec and wins over `design.md`
 * when both exist.
 *
 * Reel writes it from the look the film was composed in, so the spec and the
 * cut cannot disagree — and so an agent editing a scene afterwards has the
 * tokens to hand rather than having to read them back out of the CSS.
 */
export function frameMd(look: Look, accent: string, name: string, frame: { width: number; height: number }): string {
  return `---
name: ${name} — ${look.name}
format: ${frame.width}x${frame.height}
colors:
  ground: "${look.ground}"
  ink: "${look.ink}"
  muted: "${look.muted}"
  accent: "${accent}"
typography:
  display:
    fontFamily: ${look.display}
    fontWeight: ${look.displayWeight}
    letterSpacing: "${look.tracking}"
    textTransform: ${look.transform}
  label:
    fontFamily: ${look.label}
    letterSpacing: "0.26em"
    textTransform: uppercase
motion:
  entrance: waterfall
  wordDuration: 0.16s
  ease: power4.out
  handoff: 0.5s
---

# ${name} — the frame

Generated by \`reel compose\` from the **${look.name}** look. ${look.mood}

## The frame

The unit is the frame, not the page. One very large element and everything else
small; a card that tries to be balanced reads as a slide.

## Colour

\`accent\` is the brand's, and every backdrop in this film is built out of it —
hue-rotated, tinted, blurred. That is deliberate: the same look on two products
should not produce the same picture. Ground and ink belong to the look and
should not be edited per scene.

## Motion

Arrivals are **binary and fast**. A word is revealed with a zero-duration
\`set\` and whipped into place in ~0.16s on \`power4.out\`; it is never faded in.
Fading an arrival is the single change that turns a title card into a slide.

Backdrops move for a scene's whole duration. A bloom that stops once the words
have landed leaves the frame dead for the rest of the shot.

## Do

- Cut on the beats in \`shots.json\`. They are exact, because the driver caused them.
- Keep cards to 2.5–3.5s.
- Let scenes dissolve into each other; the handoff lives inside the outgoing scene.

## Don't

- Don't crop the footage to fill the frame. A product demo cropped loses the
  thing it is about.
- Don't lay text over the picture. The app moves; a bottom band does not collide.
- Don't fade a clip element — fade its \`#root\`, inside the sub-composition.
`;
}

/**
 * `STORYBOARD.md` — the plan layer.
 *
 * Their format: YAML frontmatter for global direction, then one
 * `## Frame N — Title` per scene with `- key: value` metadata. The parser is
 * lenient and Studio renders it as a contact sheet, so it is worth writing
 * properly even though nothing here reads it back yet.
 */
export function storyboardMd(
  frames: SceneFrame[],
  opts: { name: string; width: number; height: number; duration: number; message: string },
): string {
  const head = `---
format: ${opts.width}x${opts.height}
duration: ${opts.duration.toFixed(1)}s
message: ${opts.message}
arc: Title → Product → Chapter → Command line → Close
audience: developers evaluating the tool
mode: autonomous
---

# ${opts.name}

Assembled by \`reel compose\`. Every frame below is a sub-composition mounted by
\`index.html\`; the footage frames are real recordings of the running app, and
their captions and camera moves are timed from the shot manifest the driver
wrote while filming.
`;

  const body = frames
    .map(
      (f, i) => `
## Frame ${i + 1} — ${f.title}

- status: animated
- src: ${f.src}
- duration: ${f.duration.toFixed(2)}s
- transition_in: ${f.transitionIn}
- scene: ${f.scene}
- poster: ${f.poster.toFixed(2)}
`,
    )
    .join("");

  return head + body;
}

/**
 * `index.html` — the assembly layer, and nothing else.
 *
 * Each scene is a host clip carrying `data-composition-src` plus its own
 * `data-start` / `data-duration` / `data-track-index` / `data-width` /
 * `data-height`. The host's `data-composition-id` must equal the id inside the
 * mounted file *and* the key that file registers its timeline under; a mismatch
 * passes lint and then waits 45 seconds per scene at render before capturing
 * static frames.
 *
 * There is no timeline here on purpose. Every scene owns its own motion,
 * including its handoff, so the index stays a running order — which is what
 * makes a scene editable without reading the rest of the cut.
 */
export function indexHtml(
  frames: SceneFrame[],
  look: Look,
  opts: { id: string; width: number; height: number; fps: number; duration: number },
): string {
  const clips = frames
    .map(
      (f, i) =>
        // Every host clip carries an id. Without one Studio has no stable edit
        // target for its timeline and canvas controls, and `check` says so.
        `    <div id="scene-${f.id}" data-composition-id="${f.id}"\n` +
        `         data-composition-src="${f.src}"\n` +
        `         data-start="${f.at.toFixed(3)}" data-duration="${f.duration.toFixed(3)}"\n` +
        `         data-track-index="${i}" data-width="${opts.width}" data-height="${opts.height}"></div>`,
    )
    .join("\n\n");

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <!-- Vendored, never linked. A render that fetches depends on someone
         else's uptime and fails outright in a sandbox. -->
    <script src="./gsap.min.js"></script>
    <style>
${fontFaces(look.display, look.label)}
      * { margin: 0; padding: 0; box-sizing: border-box; }
      html, body { width: ${opts.width}px; height: ${opts.height}px; overflow: hidden; background: #000; }
      #root { position: relative; overflow: hidden; background: ${look.ground}; }
      /* The grade sits over every scene for the whole film — a vignette that
         breathes, and the one thing the index itself animates. Untimed, so it
         needs its own layout: the runtime only positions elements carrying
         data-start. */
      #grade { position: absolute; inset: 0; pointer-events: none; z-index: 50;
        background: radial-gradient(ellipse at 50% 48%, transparent 52%,
          ${look.dark ? "rgba(0,0,0,.55)" : "rgba(20,16,12,.28)"} 100%); }
    </style>
  </head>
  <body>
    <div id="root" data-composition-id="${opts.id}" data-start="0"
         data-duration="${opts.duration.toFixed(3)}"
         data-width="${opts.width}" data-height="${opts.height}" data-fps="${opts.fps}">

${clips}

      <div id="grade"></div>
    </div>

    <script>
      // The host registers a timeline of its own. The runtime auto-nests every
      // registered child timeline under it, so this file stays a running order
      // — but a composition with no registry entry at all is an error, and the
      // grade gives this one something real to drive.
      var tl = gsap.timeline({ paused: true });
      tl.fromTo("#grade", { opacity: .55 }, { opacity: .95, duration: ${opts.duration.toFixed(3)}, ease: "none" }, 0);
      window.__timelines["${opts.id}"] = tl;
    </script>
  </body>
</html>
`;
}

/** The manifest that makes a directory a project its CLI recognises. */
export function hyperframesJson(name: string): string {
  return JSON.stringify({ name, entry: "index.html" }, null, 2) + "\n";
}
