// Write demo/script.md from the chapter specs.
//
// The narration lives in the specs, because that is what Reel reads and what
// gets rendered. This produces the readable version for review, rather than a
// second copy of the words that would quietly disagree with the first.
//
//   node demo/script.mjs
import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";

const demoDir = dirname(fileURLToPath(import.meta.url));
const chapterDir = join(demoDir, "chapters");

/** A `say:` is either the line itself or `{ text, ms }`. */
function said(value) {
  if (typeof value === "string") return value;
  if (value && typeof value === "object" && typeof value.text === "string") return value.text;
  return null;
}

/** Every spoken line in a spec, in order: standalone steps, cards, captions. */
function lines(spec) {
  const out = [];
  for (const step of spec.steps ?? []) {
    if (typeof step !== "object" || step === null) continue;
    const line = said(step.say) ?? said(step.card?.say) ?? said(step.caption?.say);
    if (line) out.push(line);
  }
  return out;
}

const files = (await readdir(chapterDir)).filter((f) => f.endsWith(".reel.yaml")).sort();
const md = ["# The tour, as spoken", ""];
md.push(
  "Generated by `node demo/script.mjs` from the chapter specs — edit the `say:`",
  "lines there, not here. A changed line re-synthesizes only itself; the rest",
  "come back from `.reel-cache/voice`.",
  "",
);

let words = 0;
let chars = 0;
for (const file of files) {
  const spec = parse(await readFile(join(chapterDir, file), "utf8"));
  const said = lines(spec);
  const w = said.join(" ").split(/\s+/).filter(Boolean).length;
  const c = said.join(" ").length;
  words += w;
  chars += c;
  md.push(`## ${spec.name}`, "", `\`${file}\` · ${said.length} lines · ${w} words`, "");
  for (const line of said) md.push(`> ${line.replace(/\s+/g, " ").trim()}`, "");
}

// Roughly 150 words a minute, which is where a measured narration lands.
md.push("---", "", `**${files.length} chapters · ${words} words · ${chars} characters · about ${(words / 150).toFixed(1)} minutes spoken.**`, "");

await writeFile(join(demoDir, "script.md"), md.join("\n"));
console.log(`wrote demo/script.md — ${files.length} chapters, ${words} words, ~${(words / 150).toFixed(1)} min`);
